name: Build RustDesk Windows Client

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up MSVC build tools
        uses: ilammy/msvc-dev-cmd@v1

      - name: Ensure vcpkg.json has correct dependencies (opus, libvpx, libyuv)
        run: |
          $json = Get-Content vcpkg.json | ConvertFrom-Json
          $json.dependencies = @("opus", "libvpx", "libyuv")
          $json | ConvertTo-Json -Depth 10 | Set-Content vcpkg.json

      - name: Clone vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git

      - name: Bootstrap vcpkg
        run: |
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install RustDesk dependencies via vcpkg (manifest mode, static triplet)
        run: |
          .\vcpkg\vcpkg install --triplet x64-windows-static

      - name: Install LLVM/Clang
        run: |
          choco install llvm -y

      - name: Build (cargo)
        env:
          RELAY_SERVER: rust.northwoodscomputerguy.com
          RENDEZVOUS_SERVER: rust.northwoodscomputerguy.com
          KEY: sjVK2P8Cik7MW4v6sn1FhCN5RdRAK1BpqXlSDraF0qY=
          VCPKG_ROOT: ${{ github.workspace }}\vcpkg
        run: |
          cargo build --release --locked

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-exe
          path: target\release\rustdesk.exe
