name: Build RustDesk Windows Client

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up MSVC build tools
        uses: ilammy/msvc-dev-cmd@v1

      # Split vcpkg steps for better logs/troubleshooting
      - name: Clone vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git

      - name: Bootstrap vcpkg
        run: |
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install opus via vcpkg
        run: |
          .\vcpkg\vcpkg install opus:x64-windows-static

      # The actual build step, with your pre-configured servers
      - name: Build (cargo)
        env:
          RELAY_SERVER: rust.northwoodscomputerguy.com
          RENDEZVOUS_SERVER: rust.northwoodscomputerguy.com
          KEY: sjVK2P8Cik7MW4v6sn1FhCN5RdRAK1BpqXlSDraF0qY=
          VCPKG_ROOT: ${{ github.workspace }}\vcpkg
        run: |
          cargo build --release --locked

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-exe
          path: target\release\rustdesk.exe

