name: Build RustDesk Windows Client

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up MSVC build tools
        uses: ilammy/msvc-dev-cmd@v1

      - name: Ensure vcpkg.json has correct dependencies (opus, libvpx, libyuv, aom)
        run: |
          $json = Get-Content vcpkg.json | ConvertFrom-Json
          $json.dependencies = @("opus", "libvpx", "libyuv", "aom")
          $json | ConvertTo-Json -Depth 10 | Set-Content vcpkg.json

      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Install RustDesk dependencies via vcpkg (manifest mode, static triplet)
        run: .\vcpkg\vcpkg install --triplet x64-windows-static

      - name: Force classic opus/libvpx/libyuv/aom install (CI workaround)
        run: .\vcpkg\vcpkg install opus:x64-windows-static libvpx:x64-windows-static libyuv:x64-windows-static aom:x64-windows-static --classic

      - name: Install LLVM/Clang
        run: choco install llvm -y

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get Flutter dependencies
        working-directory: flutter
        run: flutter pub get

      - name: Generate FFI bridge files (RustDesk native script)
        working-directory: flutter
        shell: pwsh
        run: |
          if (Test-Path ./gen_bridge_files.bat) { ./gen_bridge_files.bat }
          if (Test-Path ./gen_bridge_files.ps1) { ./gen_bridge_files.ps1 }
          if (Test-Path ./gen_bridge_files.sh) { bash ./gen_bridge_files.sh }

      - name: Build RustDesk Windows GUI (Flutter)
        working-directory: flutter
        run: flutter build windows

      # Debug step: show all EXEs under the Release build folder (can be removed later)
      - name: List built EXEs for artifact path debugging
        run: Get-ChildItem -Path flutter\build\windows\runner\Release -Recurse -Filter *.exe

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-exe
          path: flutter/build/windows/runner/Release/rustdesk.exe
